[run]
command = "npm run dev:all"

[workflows]
"Start application" = "npm run dev:all"

[deployment]
run = ["npm", "run", "start"]

[languages.javascript]
pattern = "**/{*.js,*.jsx,*.ts,*.tsx}"
[languages.javascript.languageServer]
start = "typescript-language-server --stdio"